steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/alpine-comfort-268715/cloudrun-demo:${SHORT_SHA}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/alpine-comfort-268715/cloudrun-demo"]